// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"ginTonicProject/handler"
	"ginTonicProject/service"
)

// Injectors from wire.go:

func InitializeUserHandler() *handler.UserHandler {
	userService := service.NewUserService()
	userHandler := handler.NewUserHandler(userService)
	return userHandler
}
