// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"ginTonicProject/config"
	"ginTonicProject/handler"
	"ginTonicProject/repository"
	"ginTonicProject/service"
)

// Injectors from wire.go:

func InitializeUserHandler() *handler.UserHandler {
	configConfig := config.MustLoadConfig()
	db := config.InitDB(configConfig)
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	return userHandler
}
